services:
  myportfolio:
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - mysql

  mysql:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mydatabase:/var/lib/mysql

  nginx:
    image: jonasal/nginx-certbot:latest
    restart: always
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d
    depends_on:
      - myportfolio

volumes:
  mydatabase:
  nginx_secrets:
